server:
  port: 8080
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.gmail.mosoft521.cp.jxc.entity
  mapper-locations:
    - classpath:mybatis/dao/**/*.xml

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/jxc4?useUnicode=true&characterEncoding=UTF8
    username: root
    password: admin
    dbcp2:
      min-idle: 5
      initial-size: 10
      max-total: 10
      max-wait-millis: 200
  resources:
    static-locations: ["classpath:/static/","classpath:/templates/demo/datagrid","classpath:/","classpath:/templates"]

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  offset-as-page-num: true
  row-bounds-with-count: true